# ==============================================================================
# Service Accounts
# ==============================================================================

# ------------------------------------------------------------------------------
# 1. Service Account for Frontend Application
# ------------------------------------------------------------------------------
apiVersion: v1 # Kubernetes API version for ServiceAccount resources
kind: ServiceAccount    
metadata:
  name: frontend-sa # Kubernetes API version for ServiceAccount resources
  namespace: aegis # Kubernetes namespace where the resource is created

---
# The '---' separator indicates the start of a new resource in the same file.

# ------------------------------------------------------------------------------
# 2. Service Account for Backend Application
# ------------------------------------------------------------------------------
apiVersion: v1         
kind: ServiceAccount    
metadata:
  name: backend-sa # Unique service account name for Backend
  namespace: aegis      

---

# ------------------------------------------------------------------------------
# 3. Service Account for PostgreSQL Database
# ------------------------------------------------------------------------------
apiVersion: v1          
kind: ServiceAccount    
metadata:
  name: postgres-sa # Unique service account name for PostgreSQL
  namespace: aegis     