apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: aegis
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: aegis
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: aegis
